## Goal ##

# action_type should accord with action.proto or planningResponse in exec_monitor.cpp
# 0: GOTO
# 1: ...
int8 action_type

PoseEuler pose
bool set_orientation
---
## Result ##

---
## Feedback ##
