// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

#ifndef PROTOBUF_command_2eproto__INCLUDED
#define PROTOBUF_command_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace urs_protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_command_2eproto();
void protobuf_AssignDesc_command_2eproto();
void protobuf_ShutdownFile_command_2eproto();

class Command;

enum Command_CommandType {
  Command_CommandType_GOTO = 0,
  Command_CommandType_MOVE = 1
};
bool Command_CommandType_IsValid(int value);
const Command_CommandType Command_CommandType_CommandType_MIN = Command_CommandType_GOTO;
const Command_CommandType Command_CommandType_CommandType_MAX = Command_CommandType_MOVE;
const int Command_CommandType_CommandType_ARRAYSIZE = Command_CommandType_CommandType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Command_CommandType_descriptor();
inline const ::std::string& Command_CommandType_Name(Command_CommandType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Command_CommandType_descriptor(), value);
}
inline bool Command_CommandType_Parse(
    const ::std::string& name, Command_CommandType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Command_CommandType>(
    Command_CommandType_descriptor(), name, value);
}
// ===================================================================

class Command : public ::google::protobuf::Message {
 public:
  Command();
  virtual ~Command();

  Command(const Command& from);

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Command& default_instance();

  void Swap(Command* other);

  // implements Message ----------------------------------------------

  Command* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Command& from);
  void MergeFrom(const Command& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Command_CommandType CommandType;
  static const CommandType GOTO = Command_CommandType_GOTO;
  static const CommandType MOVE = Command_CommandType_MOVE;
  static inline bool CommandType_IsValid(int value) {
    return Command_CommandType_IsValid(value);
  }
  static const CommandType CommandType_MIN =
    Command_CommandType_CommandType_MIN;
  static const CommandType CommandType_MAX =
    Command_CommandType_CommandType_MAX;
  static const int CommandType_ARRAYSIZE =
    Command_CommandType_CommandType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CommandType_descriptor() {
    return Command_CommandType_descriptor();
  }
  static inline const ::std::string& CommandType_Name(CommandType value) {
    return Command_CommandType_Name(value);
  }
  static inline bool CommandType_Parse(const ::std::string& name,
      CommandType* value) {
    return Command_CommandType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .urs_protobuf.Command.CommandType command_type = 1;
  inline bool has_command_type() const;
  inline void clear_command_type();
  static const int kCommandTypeFieldNumber = 1;
  inline ::urs_protobuf::Command_CommandType command_type() const;
  inline void set_command_type(::urs_protobuf::Command_CommandType value);

  // optional int32 uav_id = 2;
  inline bool has_uav_id() const;
  inline void clear_uav_id();
  static const int kUavIdFieldNumber = 2;
  inline ::google::protobuf::int32 uav_id() const;
  inline void set_uav_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:urs_protobuf.Command)
 private:
  inline void set_has_command_type();
  inline void clear_has_command_type();
  inline void set_has_uav_id();
  inline void clear_has_uav_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int command_type_;
  ::google::protobuf::int32 uav_id_;
  friend void  protobuf_AddDesc_command_2eproto();
  friend void protobuf_AssignDesc_command_2eproto();
  friend void protobuf_ShutdownFile_command_2eproto();

  void InitAsDefaultInstance();
  static Command* default_instance_;
};
// ===================================================================


// ===================================================================

// Command

// required .urs_protobuf.Command.CommandType command_type = 1;
inline bool Command::has_command_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Command::set_has_command_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Command::clear_has_command_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Command::clear_command_type() {
  command_type_ = 0;
  clear_has_command_type();
}
inline ::urs_protobuf::Command_CommandType Command::command_type() const {
  // @@protoc_insertion_point(field_get:urs_protobuf.Command.command_type)
  return static_cast< ::urs_protobuf::Command_CommandType >(command_type_);
}
inline void Command::set_command_type(::urs_protobuf::Command_CommandType value) {
  assert(::urs_protobuf::Command_CommandType_IsValid(value));
  set_has_command_type();
  command_type_ = value;
  // @@protoc_insertion_point(field_set:urs_protobuf.Command.command_type)
}

// optional int32 uav_id = 2;
inline bool Command::has_uav_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Command::set_has_uav_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Command::clear_has_uav_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Command::clear_uav_id() {
  uav_id_ = 0;
  clear_has_uav_id();
}
inline ::google::protobuf::int32 Command::uav_id() const {
  // @@protoc_insertion_point(field_get:urs_protobuf.Command.uav_id)
  return uav_id_;
}
inline void Command::set_uav_id(::google::protobuf::int32 value) {
  set_has_uav_id();
  uav_id_ = value;
  // @@protoc_insertion_point(field_set:urs_protobuf.Command.uav_id)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace urs_protobuf

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::urs_protobuf::Command_CommandType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::urs_protobuf::Command_CommandType>() {
  return ::urs_protobuf::Command_CommandType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_command_2eproto__INCLUDED
