// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

#ifndef PROTOBUF_state_2eproto__INCLUDED
#define PROTOBUF_state_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "predicate.pb.h"
// @@protoc_insertion_point(includes)

namespace pb_urs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_state_2eproto();
void protobuf_AssignDesc_state_2eproto();
void protobuf_ShutdownFile_state_2eproto();

class State;
class State_OneofPredicate;

// ===================================================================

class State_OneofPredicate : public ::google::protobuf::Message {
 public:
  State_OneofPredicate();
  virtual ~State_OneofPredicate();

  State_OneofPredicate(const State_OneofPredicate& from);

  inline State_OneofPredicate& operator=(const State_OneofPredicate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const State_OneofPredicate& default_instance();

  void Swap(State_OneofPredicate* other);

  // implements Message ----------------------------------------------

  State_OneofPredicate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const State_OneofPredicate& from);
  void MergeFrom(const State_OneofPredicate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pb_urs.At at = 1;
  inline int at_size() const;
  inline void clear_at();
  static const int kAtFieldNumber = 1;
  inline const ::pb_urs::At& at(int index) const;
  inline ::pb_urs::At* mutable_at(int index);
  inline ::pb_urs::At* add_at();
  inline const ::google::protobuf::RepeatedPtrField< ::pb_urs::At >&
      at() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb_urs::At >*
      mutable_at();

  // @@protoc_insertion_point(class_scope:pb_urs.State.OneofPredicate)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pb_urs::At > at_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static State_OneofPredicate* default_instance_;
};
// -------------------------------------------------------------------

class State : public ::google::protobuf::Message {
 public:
  State();
  virtual ~State();

  State(const State& from);

  inline State& operator=(const State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const State& default_instance();

  void Swap(State* other);

  // implements Message ----------------------------------------------

  State* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const State& from);
  void MergeFrom(const State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef State_OneofPredicate OneofPredicate;

  // accessors -------------------------------------------------------

  // repeated .pb_urs.State.OneofPredicate oneof_predicate = 1;
  inline int oneof_predicate_size() const;
  inline void clear_oneof_predicate();
  static const int kOneofPredicateFieldNumber = 1;
  inline const ::pb_urs::State_OneofPredicate& oneof_predicate(int index) const;
  inline ::pb_urs::State_OneofPredicate* mutable_oneof_predicate(int index);
  inline ::pb_urs::State_OneofPredicate* add_oneof_predicate();
  inline const ::google::protobuf::RepeatedPtrField< ::pb_urs::State_OneofPredicate >&
      oneof_predicate() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb_urs::State_OneofPredicate >*
      mutable_oneof_predicate();

  // repeated .pb_urs.At at = 2;
  inline int at_size() const;
  inline void clear_at();
  static const int kAtFieldNumber = 2;
  inline const ::pb_urs::At& at(int index) const;
  inline ::pb_urs::At* mutable_at(int index);
  inline ::pb_urs::At* add_at();
  inline const ::google::protobuf::RepeatedPtrField< ::pb_urs::At >&
      at() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb_urs::At >*
      mutable_at();

  // @@protoc_insertion_point(class_scope:pb_urs.State)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pb_urs::State_OneofPredicate > oneof_predicate_;
  ::google::protobuf::RepeatedPtrField< ::pb_urs::At > at_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static State* default_instance_;
};
// ===================================================================


// ===================================================================

// State_OneofPredicate

// repeated .pb_urs.At at = 1;
inline int State_OneofPredicate::at_size() const {
  return at_.size();
}
inline void State_OneofPredicate::clear_at() {
  at_.Clear();
}
inline const ::pb_urs::At& State_OneofPredicate::at(int index) const {
  // @@protoc_insertion_point(field_get:pb_urs.State.OneofPredicate.at)
  return at_.Get(index);
}
inline ::pb_urs::At* State_OneofPredicate::mutable_at(int index) {
  // @@protoc_insertion_point(field_mutable:pb_urs.State.OneofPredicate.at)
  return at_.Mutable(index);
}
inline ::pb_urs::At* State_OneofPredicate::add_at() {
  // @@protoc_insertion_point(field_add:pb_urs.State.OneofPredicate.at)
  return at_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb_urs::At >&
State_OneofPredicate::at() const {
  // @@protoc_insertion_point(field_list:pb_urs.State.OneofPredicate.at)
  return at_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb_urs::At >*
State_OneofPredicate::mutable_at() {
  // @@protoc_insertion_point(field_mutable_list:pb_urs.State.OneofPredicate.at)
  return &at_;
}

// -------------------------------------------------------------------

// State

// repeated .pb_urs.State.OneofPredicate oneof_predicate = 1;
inline int State::oneof_predicate_size() const {
  return oneof_predicate_.size();
}
inline void State::clear_oneof_predicate() {
  oneof_predicate_.Clear();
}
inline const ::pb_urs::State_OneofPredicate& State::oneof_predicate(int index) const {
  // @@protoc_insertion_point(field_get:pb_urs.State.oneof_predicate)
  return oneof_predicate_.Get(index);
}
inline ::pb_urs::State_OneofPredicate* State::mutable_oneof_predicate(int index) {
  // @@protoc_insertion_point(field_mutable:pb_urs.State.oneof_predicate)
  return oneof_predicate_.Mutable(index);
}
inline ::pb_urs::State_OneofPredicate* State::add_oneof_predicate() {
  // @@protoc_insertion_point(field_add:pb_urs.State.oneof_predicate)
  return oneof_predicate_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb_urs::State_OneofPredicate >&
State::oneof_predicate() const {
  // @@protoc_insertion_point(field_list:pb_urs.State.oneof_predicate)
  return oneof_predicate_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb_urs::State_OneofPredicate >*
State::mutable_oneof_predicate() {
  // @@protoc_insertion_point(field_mutable_list:pb_urs.State.oneof_predicate)
  return &oneof_predicate_;
}

// repeated .pb_urs.At at = 2;
inline int State::at_size() const {
  return at_.size();
}
inline void State::clear_at() {
  at_.Clear();
}
inline const ::pb_urs::At& State::at(int index) const {
  // @@protoc_insertion_point(field_get:pb_urs.State.at)
  return at_.Get(index);
}
inline ::pb_urs::At* State::mutable_at(int index) {
  // @@protoc_insertion_point(field_mutable:pb_urs.State.at)
  return at_.Mutable(index);
}
inline ::pb_urs::At* State::add_at() {
  // @@protoc_insertion_point(field_add:pb_urs.State.at)
  return at_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb_urs::At >&
State::at() const {
  // @@protoc_insertion_point(field_list:pb_urs.State.at)
  return at_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb_urs::At >*
State::mutable_at() {
  // @@protoc_insertion_point(field_mutable_list:pb_urs.State.at)
  return &at_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb_urs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_state_2eproto__INCLUDED
