(define (domain urs)
  (:requirements :conditional-effects :typing :equality)
  (:types uav_id wp_id)
  (:predicates
    (at ?id - uav_id ?wp - wp_id)
  )
  (:action goto
    :parameters (?id - uav_id ?wp0 - wp_id ?wp1 - wp_id)
    :precondition (at ?id ?wp0)
    :effect (and (not (at ?id ?wp0)) (at ?id ?wp1))
  )
)
(define (problem urs_prob)
  (:domain urs)
  (:objects uav_id0 uav_id1 uav_id2 uav_id3 - uav_id wp_id0 wp_id1 wp_id2 wp_id3 wp_id4 wp_id5 - wp_id)
  (:init (and (at uav_id0 wp_id0)(at uav_id1 wp_id1)(at uav_id2 wp_id2)(at uav_id3 wp_id3)))
  (:goal (and (at uav_id0 wp_id4)(at uav_id1 wp_id5)))
)