// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: predicate.proto

#ifndef PROTOBUF_predicate_2eproto__INCLUDED
#define PROTOBUF_predicate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb_urs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_predicate_2eproto();
void protobuf_AssignDesc_predicate_2eproto();
void protobuf_ShutdownFile_predicate_2eproto();

class At;

// ===================================================================

class At : public ::google::protobuf::Message {
 public:
  At();
  virtual ~At();

  At(const At& from);

  inline At& operator=(const At& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const At& default_instance();

  void Swap(At* other);

  // implements Message ----------------------------------------------

  At* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const At& from);
  void MergeFrom(const At& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 uav_id = 1;
  inline bool has_uav_id() const;
  inline void clear_uav_id();
  static const int kUavIdFieldNumber = 1;
  inline ::google::protobuf::int32 uav_id() const;
  inline void set_uav_id(::google::protobuf::int32 value);

  // optional double x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline double x() const;
  inline void set_x(double value);

  // optional double y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline double y() const;
  inline void set_y(double value);

  // optional double z = 4;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 4;
  inline double z() const;
  inline void set_z(double value);

  // optional double yaw = 5;
  inline bool has_yaw() const;
  inline void clear_yaw();
  static const int kYawFieldNumber = 5;
  inline double yaw() const;
  inline void set_yaw(double value);

  // @@protoc_insertion_point(class_scope:pb_urs.At)
 private:
  inline void set_has_uav_id();
  inline void clear_has_uav_id();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_yaw();
  inline void clear_has_yaw();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  double yaw_;
  ::google::protobuf::int32 uav_id_;
  friend void  protobuf_AddDesc_predicate_2eproto();
  friend void protobuf_AssignDesc_predicate_2eproto();
  friend void protobuf_ShutdownFile_predicate_2eproto();

  void InitAsDefaultInstance();
  static At* default_instance_;
};
// ===================================================================


// ===================================================================

// At

// optional int32 uav_id = 1;
inline bool At::has_uav_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void At::set_has_uav_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void At::clear_has_uav_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void At::clear_uav_id() {
  uav_id_ = 0;
  clear_has_uav_id();
}
inline ::google::protobuf::int32 At::uav_id() const {
  // @@protoc_insertion_point(field_get:pb_urs.At.uav_id)
  return uav_id_;
}
inline void At::set_uav_id(::google::protobuf::int32 value) {
  set_has_uav_id();
  uav_id_ = value;
  // @@protoc_insertion_point(field_set:pb_urs.At.uav_id)
}

// optional double x = 2;
inline bool At::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void At::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void At::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void At::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double At::x() const {
  // @@protoc_insertion_point(field_get:pb_urs.At.x)
  return x_;
}
inline void At::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:pb_urs.At.x)
}

// optional double y = 3;
inline bool At::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void At::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void At::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void At::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double At::y() const {
  // @@protoc_insertion_point(field_get:pb_urs.At.y)
  return y_;
}
inline void At::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:pb_urs.At.y)
}

// optional double z = 4;
inline bool At::has_z() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void At::set_has_z() {
  _has_bits_[0] |= 0x00000008u;
}
inline void At::clear_has_z() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void At::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double At::z() const {
  // @@protoc_insertion_point(field_get:pb_urs.At.z)
  return z_;
}
inline void At::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:pb_urs.At.z)
}

// optional double yaw = 5;
inline bool At::has_yaw() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void At::set_has_yaw() {
  _has_bits_[0] |= 0x00000010u;
}
inline void At::clear_has_yaw() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void At::clear_yaw() {
  yaw_ = 0;
  clear_has_yaw();
}
inline double At::yaw() const {
  // @@protoc_insertion_point(field_get:pb_urs.At.yaw)
  return yaw_;
}
inline void At::set_yaw(double value) {
  set_has_yaw();
  yaw_ = value;
  // @@protoc_insertion_point(field_set:pb_urs.At.yaw)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb_urs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_predicate_2eproto__INCLUDED
