// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

#ifndef PROTOBUF_state_2eproto__INCLUDED
#define PROTOBUF_state_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "predicate.pb.h"
// @@protoc_insertion_point(includes)

namespace urs_wearable_pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_state_2eproto();
void protobuf_AssignDesc_state_2eproto();
void protobuf_ShutdownFile_state_2eproto();

class State;
class State_Oneof;

// ===================================================================

class State_Oneof : public ::google::protobuf::Message {
 public:
  State_Oneof();
  virtual ~State_Oneof();

  State_Oneof(const State_Oneof& from);

  inline State_Oneof& operator=(const State_Oneof& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const State_Oneof& default_instance();

  void Swap(State_Oneof* other);

  // implements Message ----------------------------------------------

  State_Oneof* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const State_Oneof& from);
  void MergeFrom(const State_Oneof& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .urs_wearable_pb.At at = 1;
  inline int at_size() const;
  inline void clear_at();
  static const int kAtFieldNumber = 1;
  inline const ::urs_wearable_pb::At& at(int index) const;
  inline ::urs_wearable_pb::At* mutable_at(int index);
  inline ::urs_wearable_pb::At* add_at();
  inline const ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At >&
      at() const;
  inline ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At >*
      mutable_at();

  // @@protoc_insertion_point(class_scope:urs_wearable_pb.State.Oneof)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At > at_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static State_Oneof* default_instance_;
};
// -------------------------------------------------------------------

class State : public ::google::protobuf::Message {
 public:
  State();
  virtual ~State();

  State(const State& from);

  inline State& operator=(const State& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const State& default_instance();

  void Swap(State* other);

  // implements Message ----------------------------------------------

  State* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const State& from);
  void MergeFrom(const State& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef State_Oneof Oneof;

  // accessors -------------------------------------------------------

  // repeated .urs_wearable_pb.At at = 1;
  inline int at_size() const;
  inline void clear_at();
  static const int kAtFieldNumber = 1;
  inline const ::urs_wearable_pb::At& at(int index) const;
  inline ::urs_wearable_pb::At* mutable_at(int index);
  inline ::urs_wearable_pb::At* add_at();
  inline const ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At >&
      at() const;
  inline ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At >*
      mutable_at();

  // repeated .urs_wearable_pb.State.Oneof oneof = 2;
  inline int oneof_size() const;
  inline void clear_oneof();
  static const int kOneofFieldNumber = 2;
  inline const ::urs_wearable_pb::State_Oneof& oneof(int index) const;
  inline ::urs_wearable_pb::State_Oneof* mutable_oneof(int index);
  inline ::urs_wearable_pb::State_Oneof* add_oneof();
  inline const ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::State_Oneof >&
      oneof() const;
  inline ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::State_Oneof >*
      mutable_oneof();

  // @@protoc_insertion_point(class_scope:urs_wearable_pb.State)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At > at_;
  ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::State_Oneof > oneof_;
  friend void  protobuf_AddDesc_state_2eproto();
  friend void protobuf_AssignDesc_state_2eproto();
  friend void protobuf_ShutdownFile_state_2eproto();

  void InitAsDefaultInstance();
  static State* default_instance_;
};
// ===================================================================


// ===================================================================

// State_Oneof

// repeated .urs_wearable_pb.At at = 1;
inline int State_Oneof::at_size() const {
  return at_.size();
}
inline void State_Oneof::clear_at() {
  at_.Clear();
}
inline const ::urs_wearable_pb::At& State_Oneof::at(int index) const {
  // @@protoc_insertion_point(field_get:urs_wearable_pb.State.Oneof.at)
  return at_.Get(index);
}
inline ::urs_wearable_pb::At* State_Oneof::mutable_at(int index) {
  // @@protoc_insertion_point(field_mutable:urs_wearable_pb.State.Oneof.at)
  return at_.Mutable(index);
}
inline ::urs_wearable_pb::At* State_Oneof::add_at() {
  // @@protoc_insertion_point(field_add:urs_wearable_pb.State.Oneof.at)
  return at_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At >&
State_Oneof::at() const {
  // @@protoc_insertion_point(field_list:urs_wearable_pb.State.Oneof.at)
  return at_;
}
inline ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At >*
State_Oneof::mutable_at() {
  // @@protoc_insertion_point(field_mutable_list:urs_wearable_pb.State.Oneof.at)
  return &at_;
}

// -------------------------------------------------------------------

// State

// repeated .urs_wearable_pb.At at = 1;
inline int State::at_size() const {
  return at_.size();
}
inline void State::clear_at() {
  at_.Clear();
}
inline const ::urs_wearable_pb::At& State::at(int index) const {
  // @@protoc_insertion_point(field_get:urs_wearable_pb.State.at)
  return at_.Get(index);
}
inline ::urs_wearable_pb::At* State::mutable_at(int index) {
  // @@protoc_insertion_point(field_mutable:urs_wearable_pb.State.at)
  return at_.Mutable(index);
}
inline ::urs_wearable_pb::At* State::add_at() {
  // @@protoc_insertion_point(field_add:urs_wearable_pb.State.at)
  return at_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At >&
State::at() const {
  // @@protoc_insertion_point(field_list:urs_wearable_pb.State.at)
  return at_;
}
inline ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::At >*
State::mutable_at() {
  // @@protoc_insertion_point(field_mutable_list:urs_wearable_pb.State.at)
  return &at_;
}

// repeated .urs_wearable_pb.State.Oneof oneof = 2;
inline int State::oneof_size() const {
  return oneof_.size();
}
inline void State::clear_oneof() {
  oneof_.Clear();
}
inline const ::urs_wearable_pb::State_Oneof& State::oneof(int index) const {
  // @@protoc_insertion_point(field_get:urs_wearable_pb.State.oneof)
  return oneof_.Get(index);
}
inline ::urs_wearable_pb::State_Oneof* State::mutable_oneof(int index) {
  // @@protoc_insertion_point(field_mutable:urs_wearable_pb.State.oneof)
  return oneof_.Mutable(index);
}
inline ::urs_wearable_pb::State_Oneof* State::add_oneof() {
  // @@protoc_insertion_point(field_add:urs_wearable_pb.State.oneof)
  return oneof_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::State_Oneof >&
State::oneof() const {
  // @@protoc_insertion_point(field_list:urs_wearable_pb.State.oneof)
  return oneof_;
}
inline ::google::protobuf::RepeatedPtrField< ::urs_wearable_pb::State_Oneof >*
State::mutable_oneof() {
  // @@protoc_insertion_point(field_mutable_list:urs_wearable_pb.State.oneof)
  return &oneof_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace urs_wearable_pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_state_2eproto__INCLUDED
